# Generated by Django 4.2.16 on 2024-12-18 13:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="username",
            field=models.TextField(default="arseven"),
            preserve_default=False,
        ),
    ]
