# Generated by Django 4.2.16 on 2024-12-18 13:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("home", "0002_booking_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="username",
        ),
    ]
